#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL

  CREATE USER $LEAPTABLE_DB_USER WITH PASSWORD '$LEAPTABLE_DB_PASS';
  ALTER USER $LEAPTABLE_DB_USER CREATEDB;

  CREATE DATABASE "$LEAPTABLE_META_DB_NAME";
  GRANT ALL PRIVILEGES ON DATABASE "$LEAPTABLE_META_DB_NAME" TO $LEAPTABLE_DB_USER;

  CREATE DATABASE "$HASURA_GRAPHQL_DB_NAME";
  GRANT ALL PRIVILEGES ON DATABASE "$HASURA_GRAPHQL_DB_NAME" TO $LEAPTABLE_DB_USER;

EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$LEAPTABLE_META_DB_NAME" <<-EOSQL

  GRANT ALL ON SCHEMA public TO $LEAPTABLE_DB_USER;

EOSQL

echo
echo "Initializing Database tables in db '$LEAPTABLE_META_DB_NAME'"
echo
# Create the database tables in the leaptable metadb.
PGPASSWORD=$LEAPTABLE_DB_PASS psql -v ON_ERROR_STOP=1 --username "$LEAPTABLE_DB_USER" \
  --dbname "$LEAPTABLE_META_DB_NAME" \
  -f /scripts/init-meta-db.sql